config/routes.rb
Shorten::Application.routes.draw do
  root to: "sh#index"
  match 'create' => 'sh#create'
  match ':short/show' => 'sh#show', :as => :show_short
  match ':short' => 'sh#redirect', :as => :redirect_short

end

app/models/short.rb
class Short < ActiveRecord::Base
  attr_accessible  :longer, :shorter
  has_one :stat, :dependent => :destroy
  after_create :create_stat

  scope :busy, lambda { |short| where('shorter = ?', short).limit(1) }

  def f
    self.longer.hash + rand.hash
  end

  def next_short
    self.shorter = f()
    ! Short.busy(self.shorter).empty?
  end
  
  def try_get_short
    i = 0
    until(!next_short or i>=10)
      i += 1
    end
  end

  before_validation :try_get_short, :if => lambda { |short| self.shorter.blank? }

  validates :shorter, :presence => true, :uniqueness => true
  validates :longer, :presence => true
  validates_format_of :longer, :with => URI::regexp(['http'])
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :short
  attr_defaults :chrome => 0, :firefox => 0, :ie => 0, :opera => 0, :other => 0, :safari => 0

  def up(ua)
    browser = Browser.new(:ua => ua)
    
    if browser.firefox?
      Stat.increment_counter :firefox, id
    elsif browser.chrome?
      Stat.increment_counter :chrome, id
    elsif browser.ie?
      Stat.increment_counter :ie, id
    elsif browser.opera?
      Stat.increment_counter :opera, id
    elsif browser.safari?
      Stat.increment_counter :safari, id
    elsif browser.other?
      Stat.increment_counter :other, id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sh_controller.rb
class ShController < ApplicationController
  def index
    @short = Short.new
  end

  def create
    @short = Short.new(params[:short])

    respond_to do |format|
      if @short.save
        format.html { redirect_to show_short_path(:short => @short.shorter) }
        format.json { render json: @short, status: :created, location: @short }
      else
        format.html { render action: "index" }
        format.json { render json: @short.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @short = Short.where('shorter = ?', params[:short]).first
  end

  def redirect
    short = Short.where('shorter = ?', params[:short]).first
    short.stat.up( request.user_agent )
    
    redirect_to "#{short.longer}"
#    respond_to do |format|
#      format.html { redirect_to "#{short.longer}" }
#    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sh_helper.rb
module ShHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorten</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sh/index.html.erb
<h1>Make your url shorter</h1>

<%= form_for(@short, :url=>{:action => 'create'}) do |f| %>
  <% if @short.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short.errors.count, "error") %> prohibited this short from being saved:</h2>

      <ul>
      <% @short.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'URL' %><br />
    <%= f.text_field :longer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sh/show.html.erb
<h1>Short info</h1>

<p>Long url: <b><%= link_to @short.longer, @short.longer %></b></p>
<p>Short url: <b><%= link_to redirect_short_url(:short => @short.shorter), redirect_short_url(:short => @short.shorter) %></b></p>

<p>Statistics</p>
<ul>
  <li>Firefox: <b><%= @short.stat.firefox %></b></li>
  <li>Opera: <b><%= @short.stat.opera %></b></li>
  <li>Chrome: <b><%= @short.stat.chrome %></b></li>
  <li>Safari: <b><%= @short.stat.safari %></b></li>
  <li>IE: <b><%= @short.stat.ie %></b></li>
  <li>Other: <b><%= @short.stat.other %></b></li>
</ul>

<%= link_to 'Back', root_path %>  